### ISSUE TITLE
Einen allgemeinen Hinweis zu Updates unterbringen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/demo_community#10]
Sowas in etwa: 

Es handelt sich hierbei um eine Demo, die für den aktuellen Stand der Addons zum Zeitpunkt der Demoerstellung gedacht ist. Vor der Aktualisierung diverser Addons, sollte geprüft werden ob diese noch kompatibel mit der installieren Demo sind. Beachtet dazu bitte die Hinweise im Installer.

**Comment by DavidBruchmann** [comment]
... mit der installier**t**en Demo ...

Ungeprüft; dann müssen Versionsangaben verfügbar sein.

**Comment by polarpixel** [comment]
Die Versionsangaben sind in der yaml-Datei, aber das ist natürlich zu versteckt.
Das Problem wird sich aber mit #15(https://github.com/FriendsOfREDAXO/demo_community/pull/15) etwas relativieren, da dort eine spezifische Version installiert der AddOns installiert wird.
Dennoch ist ein Hinweis natürlich sinnvoll, um auf mögliche Probleme durch ein manuelles Update zumindest aufmerksam zu machen.

**Comment by polarpixel** [comment]
Ich denke, das ist ok so, ich schließe hier.
