### ISSUE TITLE
Photo-Swipe für kleine Displays anpassen

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/demo_community#12]
Siehe:
http://www.redaxo.org/de/forum/allgemeines-f39/redaxo-demo-slider-bilder-grosze-t21657.html

**Comment by aeberhard** [comment]
Ich mache hier mal zu. In der aktuellen Version ist kein photoswipe auf der Startseite.
Bei Bedarf wieder aufmachen.
