### ISSUE TITLE
User-Ansicht / Feldtypen korrigieren

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/demo_community#14]
Original (bei der Installation von ycom)

![bildschirmfoto 2017-06-13 um 09 31 28](https://user-images.githubusercontent.com/3855487/27070929-3d9d8578-501b-11e7-924c-ec8d9155eded.png)

Demo-Ansicht (nicht ganz so schönes Layout, falscher Feldtyp bei Letzter Login bspw.)

![bildschirmfoto 2017-06-13 um 09 31 38](https://user-images.githubusercontent.com/3855487/27070911-348ea7be-501b-11e7-8e78-98c27feb9ec1.png)

**Comment by polarpixel** [comment]
Ist in der aktuellen Version korrigiert.
