### ISSUE TITLE
Offline Kategorien lev2 werden angezeigt

### ISSUE THREAD

**Issue by gupi** [FriendsOfREDAXO/demo_community#19]
template id 07
`					// START 2nd level categories
					foreach ($lev1->getChildren() as $lev2):
						if (rex_ycom_auth::checkPerm($lev2)) {

`
Line 43 - sollte wohl besser 

`					// START 2nd level categories
					foreach ($lev1->getChildren(**true**) as $lev2):
						if (rex_ycom_auth::checkPerm($lev2)) {

`
heißen.

**Comment by polarpixel** [comment]
Ist korrigiert, danke für den Hinweis.
