### ISSUE TITLE
Short open tags

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/demo_community#2]
Lt. http://www.redaxo.org/de/forum/post119144.html#p119144 Gibt es probleme mit short-open tags, d.h. Es wird `<?` statt `<?php` was nur unter bestimmten php.ini settings funktioniert

**Comment by polarpixel** [comment]
Das war nur versehentlich in einem Modul, hatte ich schon kurz nach Deiner Meldung korrigiert.
