### ISSUE TITLE
Probleme mit dem Link in den Mail-Templates

### ISSUE THREAD

**Issue by gupi** [FriendsOfREDAXO/demo_community#22]
Die Links in dem Mails funktionieren nicht: 
Beispiel:
$url = rex::getServer().rex_getUrl(16,'',[ 'activation_key' => REX_YFORM_DATA[field="activation_key"], 'email' => REX_YFORM_DATA[field="email"] ], '&'); 
das erzeugt bei mir seltsame Konstrukte wie: "https:/rex54:8888/http://rex54:8888/..."
Ich habe bei mir alle templates überarbeitet und den Aufruf von rex::getServer() entfernt. Damit funktionieren auch die Links.

**Comment by polarpixel** [comment]
Ist  korrigiert.
