### ISSUE TITLE
Passwortregeln

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/demo_community#24]
In der Formulardefinition für das Registrierungsformular fehlt eine Fehlermeldung und Passwortregeldefinition  in der Zeile
`ycom_auth_password|password|#placeholder:Passwort*|Dein Passwort*|`
Aktuell kommt nur eine leere Fehlermeldung man rauft sich die Haare...

**Comment by cukabeka** [comment]
Minimale passwortregel laut dirselbst: {"length":{"min":0}}
;)

**Comment by polarpixel** [comment]
Vielen Dank, ist nun korrigiert.
