### ISSUE TITLE
Nach der Installation reloaden

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/demo_community#28]
Die Erfolgsmeldung kommt erst nach dem Laden des Backendmenüs. Sinnvoller wäre es, wenn das REDAXO-Backend-Menü gleich alles zeigt, was nun vorhanden ist, statt manuell eine neue Seite aufrufen zu müssen.

**Comment by polarpixel** [comment]
Ich schließe das, da es kein Problem der Demo ist, sondern eher eines von Redaxo.
