### ISSUE TITLE
Das Verzeichnis ist nicht leer

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/demo_community#29]
`Warning: rename(/www/htdocs/.../ycomdoku/redaxo/src/addons/phpmailer.temp/phpmailer,/www/htdocs/.../ycomdoku/redaxo/src/addons/phpmailer) [<a href='https://php.net/manual/function.rename'>function.rename</a>]: Das Verzeichnis ist nicht leer in redaxo/src/addons/install/lib/archive.php on line 20`

REDAXO 5.7.0-beta1

**Comment by polarpixel** [comment]
Tritt aktuell nicht mehr auf.
