### ISSUE TITLE
Erweiterung Kommentarfunktion

### ISSUE THREAD

**Issue by TrueHatori** [FriendsOfREDAXO/demo_community#3]
Könnte man die Kommentar-Funktion um die IP des Kommentators erweitern? Und dann direkt die Möglichkeit, diese IP für weitere Besuche dieser Seite komplett zu sperren, wenn es sich um Spam oder rechtswidrige Texte im Kommentar handelt.
Eilt nicht, wäre eine feine Sache.

**Comment by polarpixel** [comment]
Das würde hier zu weit führen, denn die Demo soll ja nur den Umgang mit YCom und YForm zeigen. Zudem soll meine Kommentarfunktion nur ein schnelles Beispiel sein, wie man mit Xform eine Tabelle anlegt und damit irgendwas anstellt. In der Demo ist es auch nur registrierten Usern möglich, zu kommentieren, da wäre eine IP-Sperre ohnehin unnötig. Zumal ich behaupten würde, dass eine IP-Sperre nicht den gewünschten Effekt hat, denn die ist ja doch unproblematisch zu umgehen.

Falls Du Dir das selbst einbauen willst, dann bringt Yform schon ein IP-Feld mit: die IP speichern ist also ratz fatz erledigt. Für die Validierung müsstest Du Dir vermutlich eine der Validations aus Yform selbst erweitern. Hier kann dann ggf. das Forum helfen,

Ich schließe dann hier, sorry.
