### ISSUE TITLE
Installation in R5.7 Issues

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/demo_community#30]
Zunächst blieb es bei mir bei der GEO Plugin Installation wegen beta^2 hängen, das hängt aber ja nicht direkt mit der Demo zusammen. Vielleicht lässt sich diese Abhängigkeit aber irgendwie anders sauber lösen?

Dann aber beim import der Datenbank:
more than one field found for table: rex_ycom_user with Fieldidentifier: value, ycom_auth_password, password

Bin mir nicht sicher, ob vorher schon mal eine ycom in der DB installiert war (Testsystem), würde aber eigentlich erwarten, dass das überschrieben wird.

**Comment by polarpixel** [comment]
Ist nun behoben, die Demo ist komplett neu zusammengestöpselt
