### ISSUE TITLE
REDAXO 5.9-Kompatibilität herstellen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/demo_community#31]
_(Copy-Paste aus der Fullpage-Demo:)_

Die enthaltenen DB-Dumps sind leider nicht mit 5.9 kompatibel. Folgende Maßnahmen haben wir bereits bei der Basisdemo und der Onepage-Demo getroffen, die auch hier bei der Fullpage-Demo umgesetzt werden sollten:

1. Frisches REDAXO 5.8.1 und darin die Fullpage-Demo installieren.
2. REDAXO über den Installer auf 5.9.0 aktualisieren. Dabei wird auch die DB modifiziert.
3. Das Backup-AddOn über den Installer auf 2.5.1 aktualisieren.
4. Über das Backup-AddOn einen DB-Export erstellen. Dies wird der zukünftige utf8-Dump.
5. Das REDAXO-Setup anstoßen und in Schritt 5 (?) die Datenbank aktualisieren und dabei utf8mb4 verwenden.
6. Über das Backup-AddOn einen DB-Export erstellen. Dies wird der zukünftige utf8mb4-Dump.
7. Die beiden neuen Dumps ins den `backups`-Ordner legen und passend benennen: `demo_fullpage.utf8.sql` und `demo_fullpage.utf8mb4.sql`. Der alte Dump kann gelöscht werden.
8. In der `package.setup.yml` den Dateinamen für den Dump aktualisieren auf `demo_fullpage.utf8.sql`.
9. Den Installationsprozess erweitern wie in der Basisdemo an dieser Stelle: https://github.com/FriendsOfREDAXO/demo_base/blob/c62a425c93cc39a7c435d931cf8005e4d82ea477/pages/install.php#L115-L117
10. In der `package.yml` die Mindestversion von REDAXO auf 5.9.0 anheben. Theoretisch würden auch ältere REDAXOs noch mit dem utf8-Dump funktionieren, allerdings hat sich die Kennung im Dump geändert von `utf-8` auf `utf8`, und dafür wollten Gregor und ich in den Demos keine Sonderlocke mehr drehen ;)

**Comment by polarpixel** [comment]
Ist nun erledigt.
