### ISSUE TITLE
unvollständiger Link in Mail-Templates?

### ISSUE THREAD

**Issue by ischfr** [FriendsOfREDAXO/demo_community#36]
Ich hab diese Demo gerade zum ersten mal ausprobiert und hatte Probleme mit der Registrierung, bzw. dem Bestätigungslink in der E-Mail.

Im eigentlichen Mail-Template wird bei mir nur ein Pfad eingesetzt, aber kein Server. 
In der Anleitung ist die entsprechene Zeile länger:
`$full_url = trim(rex::getServer(),'/').trim($article_url,'.');`
Damit wird bei mir ein vollständiger Link generiert.

Ausserdem steht der Mail-Inhalt als HTML im (Non-HTML-)Body. Habe den deshalb bei mir in den HTML-Body übernommen.
Damit wird bei mir eine passende (HTML-)Mail mit klickbarem und vollständigem Link erzeugt.

Ich habe gesehen, dass es zum Link schon mal ein Issue gab, habe allerdings nicht ganz verstanden, was genau gefixt wurde.

Ich würde vorschlagen:
- die Zeile inkl. Server ins E-Mail-Template übernehmen (wie in der Anleitung)
- Body und HTML-Body im E-Mail-Template unterscheiden

**Comment by aeberhard** [comment]
Danke für den Hinweis @ischfr!
Ist mit Version 4.1.2 gefixed.
