### ISSUE TITLE
demo_community.tar.gz ist defekt

### ISSUE THREAD

**Issue by Koala** [FriendsOfREDAXO/demo_community#37]
Die Datei [demo_community.tar.gz](https://github.com/FriendsOfREDAXO/demo_community/blob/master/backups/demo_community.tar.gz] ist defekt.  Genauer: das Tar-Archiv hat einen Fehler.

Wenn versucht wird das Archiv auf einer (Linux-)Konsole zu entpacken, kommt es zur Fehlermeldung :

```
tar: A lone zero block at 16519
tar: Exiting with failure status due to previous errors
```

Es ist nicht klar, ob alle Dateien beim Entpacken mit Redaxo korrekt entpackt werden. Da die verwendete Tar-Klasse in Redaxo anders arbeitet, als das tar-Programm in einer (Linux-)Konsole, kommt es  **nicht** zu dem obigen Fehler. 

Die Datei stammt von 2020. Hier wäre eine Aktuallisierung notwendig.

Eventuell wäre auch eine Datei-/Verzeichnisliste zum Abgleich hilfreich.

**Comment by aeberhard** [comment]
Hallo Sven @Koala,
kannst Du es mal mit der angehängten Datei auf Linux probieren!?
-> [demo_base.tar.gz](https://github.com/FriendsOfREDAXO/demo_community/files/11728319/demo_base.tar.gz)

**Comment by Koala** [comment]
Keine Probleme aufgetreten.
Unter `resources` befindet sich noch eine `.DS_Store` Datei. Die könnte noch weg.
[baum.txt](https://github.com/FriendsOfREDAXO/demo_community/files/11728430/baum.txt)

**Comment by aeberhard** [comment]
Klasse! Mach ich noch weg :)

**Comment by aeberhard** [comment]
@Koala Hi Sven,
kannst Du wenn du Zeit hast mal die aktuelle Community-Demo ausprobieren. Ob da mit dem Archiv alles passt.
Danke Dir!

**Comment by aeberhard** [comment]
@Koala ich mach hier mal zu. Probleme sollten ja mittlerweile behoben sein :)
