### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by TrueHatori** [FriendsOfREDAXO/demo_community#4]
Ich bin hier bestimmt falsch, aber nur für ycom finde ich nichts.

Ich habe das Problem, dass ich beim Registrieren folgenden Fehler bekomme:
`"ErrorException" thrown in /is/htdocs/wp10477139_MJAUB0YEIY/www/ninja4ever/redaxo/src/addons/yform/lib/yform/validate/empty.php on line 18
Fatal error: Call to a member function getValue() on null`
So steht es auch unter System -> Systemlos.
Mein Formular sieht so aus:

```
objparams|form_skin|bootstrap
objparams|form_class|hide-label form-register

generate_key|activation_key
hidden|status|-1

fieldset|label|Registrieren

html|required|<p class="form-required">* Pflichtfelder</p>

text|username|#placeholder:Username*|Username*
text|email|#placeholder:E-Mail*|E-Mail*

html||<hr>

ycom_auth_password|password|#placeholder:Passwort*|Dein Passwort*|
password|password_2|#placeholder:Passwort bestätigen*|Passwort bestätigen*||no_db

captcha|Bitte Sicherheitscode eingeben|Du hast den Sicherheitscode falsch eingegeben.

validate|empty|username|Bitte Usernamen eingeben - wird Dein Login-Name
validate|unique|username|Der Name existiert bereits, bitte einen anderen wählen|rex_ycom_user
validate|email|email|Bitte gib eine gültige E-Mail ein.
validate|unique|email|Diese E-Mail existiert schon|rex_ycom_user
validate|empty|email|Bitte gib Deine E-Mail ein.
validate|empty|password|Bitte gib ein Passwort ein.
validate|compare|password|password_2||Bitte gib zweimal das gleiche Passwort ein

action|copy_value|username|login
action|db|rex_ycom_user
action|tpl2email|access_request_de|email|
```

Ich bin zwar nicht ganz sicher, aber das sollte doch eigentlich korrekt sein.
Kann das eventuell mal jemand überprüfen? Oder mir sagen, wo der Fehler liegt?

**Comment by polarpixel** [comment]
Ich nehme an, Du hast das Feld username bei Dir in der Usertabelle angelegt (mit Yform, nicht direkt in der Datenbank)?
Und Du hast bei den Einstellungen der Community dieses Felds als Login-Feld definiert?

Hier oist das Repo von Ycom, da ist es besser aufgehoben:
https://github.com/yakamara/redaxo_ycom

**Comment by staabm** [comment]
In https://github.com/yakamara/redaxo_ycom/issues/88 gehts weiter.
