### ISSUE TITLE
Source-Map-Fehler: Error: request failed with status 404

### ISSUE THREAD

**Issue by Koala** [FriendsOfREDAXO/demo_community#41]
In der Konsole beim Firefox sehe ich diese Meldung:

> Source-Map-Fehler: Error: request failed with status 404
> Ressourcen-Adresse: https://redaxo.koala/redaxo5_x_demoaddon/resources/css/bootstrap.min.css
> Source-Map-Adresse: bootstrap.min.css.map

Es scheint aber alles zu funktionieren.
Keine Ahnung, ob das wichtig ist :raised_eyebrow:

Rex: 5.15.1
Demo-Addon: 4.1.2

**Comment by aeberhard** [comment]
Hi Sven,

das ist ein Hinweis dass die Datei `bootstrap.min.css.map` nicht vorhanden ist.
Da ist noch ein Verweis in der bootstrap.min.css drin ...
`/*# sourceMappingURL=bootstrap.min.css.map */`

Man kann bei minimierten CSS-Dateien die .map-Datei auch mit ausliefern damit man im Browser bei der Quelltext-Anzeige die CSS-Datei "lesbarer" sehen kann.

Gehört natürlich weg :)

**Comment by aeberhard** [comment]
@Koala ist für die nächste Version gefixed :)
