### ISSUE TITLE
Gleiche Höhe für Teaserboxen

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/demo_community#5]
auch bei unterschiedlich viel Content die Boxen auf identische Höhe setzen

**Comment by DavidBruchmann** [comment]
https://github.com/liabru/jquery-match-height

**Comment by staabm** [comment]
-> cssgrid bitte!

**Comment by schuer** [comment]
Oder erstmal Flexbox, das wird auch noch von etwas älteren Browsern supportet. Aber bitte keine JS-Lösung.

**Comment by skerbis** [comment]
@DavidBruchmann das Skript ist nett, nur wenn es mal ein paar mehr Objekte werden als sagen wir mal 9 (meine Erfahrung) gibt es seltsame Ladeeffekte.

**Comment by polarpixel** [comment]
@skerbis Echt? Ich hatte vor, genau das einzusetzen, habe es in etlichen Projekten in Verwendung und keine Probleme damit. Aber vermutlich bin ich unter Deinem Limit von 9.
CSS ist aber auch gut, ich nehme Eure Anregung auf.

**Comment by skerbis** [comment]
Na ja, ist halt davon abhängig wie komplex der Rest des Designs ist. Da kommt es schon mal in's stolpern.

**Comment by schuer** [comment]
JS-Lösungen müssen abwarten, bis sämtlicher Content innerhalb der Boxen vollständig geladen und richtig gerendert wurde, um die Höhe zu messen. Das ist nicht ganz trivial. Hinzu kommt, dass bei dynamischen Anpassungen des Contents das Script erneut messen muss, ebenso bei Veränderungen des Viewports, falls sich dabei das Layout ändert.

Deshalb sind CSS-basierte Lösungen deutlich robuster und effizienter, denn sie überlassen das Rendering komplett dem Browser.

**Comment by AWqxKAWERbXo** [comment]
@schuer das kannst du pauschal nicht so sagen. Wenn du anfängst, Elemente noch zusätzlich zu animieren per jquery bspw, dann kann flexbox den Browser ganz schön in die Knie zwingen.

im Allgemeinen stimmt's.

**Comment by DavidBruchmann** [comment]
CSS ist meistens besser, keine Einwände,

**Comment by schuer** [comment]
6 Jahre später: Ich denke, wir sollten hier mal schließen.
Falls jemand aber weiterhin Bedarf sieht, gerne wieder öffnen!
